### ISSUE TITLE
[Feature request] Add sort options and favorites

### ISSUE THREAD

**Issue by klxiaoniu** [sdex/ActivityManager#54]
Sort app list by app name, package name, install time, update time, etc.
Favorites list, people can add frequently used activities into the list.

This app is good. Thank you very much!

**Comment by Galbert01** [comment]
Revoke this please

**Comment by drogga** [comment]
Yes, I also want to the same thing, to have a simple and easy accessible sort button to quickly change the order of the apps list to update time (latest on top).
@sdex please consider it. ;)

**Comment by sdex** [comment]
@drogga At this point I might consider only a PR :)

I was thinking about something similar to this 

![Untitled](https://github.com/sdex/ActivityManager/assets/3196011/4b1dc6ed-e6d9-4ead-a38a-41893f34b632)

Bottom sheet with access from the main screen, without the preview., just several fields to sort, order (ASC, DESC), and move display and filter toggles from settings.

**Comment by drogga** [comment]
Only a PR ? > That's unfortunate, because I don't have any coding skills, I wish I could contribute, but I can't, also I don't think we want or it needs to be so complicated, like it's a package manager like "My APK" or the "App Manager" by Muntashir Akon here on GH, only a simple/basic handful of sorting options, I don't think it makes sense to overcomplicate it, with any package details, like SDKs, ABIs and whatnot, which will probably need more permissions, dependencies/libraries or whatever and increase the package size + make it heavier, so not anything like that, just by Name (as currently), Update/install time or perhaps Package Name, even tho I don't think it's necessary or makes sense, just like ascending / descending, because I don't see why someone will need to sort them Z-A, instead of A-Z or newest on bottom - nah, I hope you have time to reconsider this and implement it if you have time in an afternoon.

**Comment by drogga** [comment]
Hi all, sorting has been implemented - Thank You @sdex.
BTW, if you don't plan to add favorites support in future, then this can/should be closed IMO.

**Comment by sdex** [comment]
I'm considering adding some quick access to an application. 
To quickly start an activity there is shortcut support.

**Comment by drogga** [comment]
I've set the sorting to latest updated on top and it turns out that the list doesn't automatically scroll to top to show the newly found and I had to manually scroll it up, because I had no idea when I launched it that there are more apps in the list and that they will show up above the default scroll point =0, you can test this by installing a new app, opening the A.M. and wait a second for the new one to be fetched (the scanning to finish) and I hope that you get what I mean, because I don't think I can explain it better than that.

**Comment by sdex** [comment]
The app already supports activity shortcuts. Application shortcuts support was added in version "5.4.8".

![Screenshot_20240205_132216](https://github.com/sdex/ActivityManager/assets/3196011/122a7805-72cb-434d-a224-e3a1083f7f5f)
