### ISSUE TITLE
How to launch app info shortcut

### ISSUE THREAD

**Issue by Zeit08** [sdex/ActivityManager#57]
Hi, can someone suggest me how do I open in one click the app info screen of a precise chosen app? 
![Screenshot_20230923-220158](https://github.com/sdex/ActivityManager/assets/45097367/c9ce9209-f807-42f1-9654-cd61f365c976)

I tried like this but I am no expert in this.

Thanks

**Comment by sdex** [comment]
![Screenshot_20230924_000259_Activity Manager.jpg](https://github.com/sdex/ActivityManager/assets/3196011/9d8c4f67-c9a4-481a-8e7d-e251d0d50959)

The action is from:
https://developer.android.com/reference/android/provider/Settings#ACTION_APPLICATION_DETAILS_SETTINGS

**Comment by sdex** [comment]
It's weird. Do you use the latest version? 
You should see the dialog  ![Screenshot_20230924_120141_Activity Manager.jpg](https://github.com/sdex/ActivityManager/assets/3196011/5ebaf020-19fa-4a64-b312-9e98bf566b79)

**Comment by sdex** [comment]
Unlikely that it's incompatibility. 
You must see the dialog to enter the name, it happens before the app creates a new shortcut. 

You can try to find some relevant logs using `adb logcat` if you have the Android SDK installed.

**Comment by sdex** [comment]
It looks like a crash. 

You can capture bug report:
https://developer.android.com/studio/debug/bug-report

**Comment by drogga** [comment]
I guess that you can normally create shortcuts from such apps like this one from an activity, instead of intent, if that's the case and you didn't forget to allow the shortcut creation from the App Info screen (in case you use a Chinese brand device, like Xiaomi, Huawei or some of those) and it indeed crashes, then the easiest method to grab/capture the crash log would be "Scoop" (fork by TacoTheDank -here on GH), but you still have to used ADB anyway to "activate" it...
