### ISSUE TITLE
[Bug]: empty activity listed

### ISSUE THREAD

**Issue by HusniMuhammad** [sdex/ActivityManager#96]
Hide unexported empty activity,
So many applications showing with this problem 

![Screenshot_20241010-171907](https://github.com/user-attachments/assets/78627920-b8e7-42dd-bc37-a30be0c5feb9)

**Comment by drogga** [comment]
IDT it's a bug/problem/issue, since that particular A.S.L. app from the screenshot has only 1 unexpored activity for me, so unless you show those, the list will be empty, but if you want the app to not be listed at all in that case, then we won't be able to locate it and see the unexported activities at all if we have them shown.

**Comment by sdex** [comment]
It's expected behavior. The app lists other applications with activities.
